### ISSUE TITLE
Test suite for Orca fails

### ISSUE THREAD

**Issue by polarvoid** [DappioWonderland/navigator#99]
Test suite for Orca ```test\orca.ts``` fails as getApr() is not a function on FarmInfoWrapper. There exists a similarily names getAprs() function.

Full Error Trace Log:

```
$ mocha --require ts-node/register --timeout 10000000 ./test/orca.ts

TSError: ⨯ Unable to compile TypeScript:
test/orca.ts:60:24 - error TS2551: Property 'getApr' does not exist on type 'FarmInfoWrapper'. Did you mean 'getAprs'?

60       const apr = farm.getApr();
                          ~~~~~~

  src/orca/infos.ts:437:3
    437   getAprs(_x: number, _y: number, _z: number, doubleDip?: boolean): number[] {
          ~~~~~~~
    'getAprs' is declared here.
test/orca.ts:61:33 - error TS2551: Property 'getApr' does not exist on type 'FarmInfoWrapper'. Did you mean 'getAprs'?

61       const doubleDipApr = farm.getApr(true);
                                   ~~~~~~

  src/orca/infos.ts:437:3
    437   getAprs(_x: number, _y: number, _z: number, doubleDip?: boolean): number[] {
          ~~~~~~~
    'getAprs' is declared here.

    at createTSError (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:843:12)
    at reportTSError (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:847:19)
    at getOutput (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:1057:36)
    at Object.compile (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:1411:41)
    at Module.m._compile (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\alvin\Developer\navigator\node_modules\ts-node\src\index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (C:\Users\alvin\Developer\navigator\node_modules\mocha\lib\nodejs\esm-utils.js:49:16)
    at async Object.exports.loadFilesAsync (C:\Users\alvin\Developer\navigator\node_modules\mocha\lib\nodejs\esm-utils.js:91:20)
    at async singleRun (C:\Users\alvin\Developer\navigator\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (C:\Users\alvin\Developer\navigator\node_modules\mocha\lib\cli\run.js:370:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Environments
Node v16.17.0
npm 8.15.0
yarn 1.22.19

How to Reproduce
Run the Orca test suite
```
npm/yarn run testOrca
```

**Comment by ironaddicteddog** [comment]
Hi @polarvoid would u like to give this issue a try?

**Comment by polarvoid** [comment]
Sure thing, could you tell me a little more about what ```getApr()``` should do?

I see functions with the same name on ```PoolInfoWrapper```, and ```getAprs()``` on ```FarmInfoWrapper``` that return a collection instead.

**Comment by Dappio-emerson** [comment]
Hi @polarvoid , 
> could you tell me a little more about what getApr() should do?

To understand this function, you'll need to know in advance what APR is.
Can know more about APR with this [link](https://www.investopedia.com/terms/a/apr.asp)

Pool in DeFi allow people swap token A for token B and there's a swap fee been charged during this process. This fee will compensate people who provide liquidity and under take the risk of impermanent loss. And we can calculate APR base on the fee generated in certain timespan.

After people who provide liquidity in pool, they will get LP(liquidity provider) token. And farm is a place people can stake their  LP token to get extra reward. So we can calculate farm's APR by the rewards / LP staked in the farm. The way protocols give out rewards might be different, so sometimes it might have multiple reward tokens, that's why in `FarmInfoWrapper` we used `getAprs()` instead of `getApr()`.

> Orca test\orca.ts fails as getApr()
And this issue is caused by miss-using `getApr()` in `FarmInfoWrapper`

**Comment by polarvoid** [comment]
Hey @Dappio-emerson,

Thank you for sharing that with me. I think I understand now, should I start working on this issue?
